# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Rebuild and restart the API server on changes
cmd = "go build -o ./tmp/api ./cmd/api"
bin = "./tmp/api"
include_ext = ["go", "tpl", "tmpl", "html", "json", "yaml", "yml"]
exclude_dir = ["tmp", "storage", "testdata", "docs"]
exclude_regex = ["_test\\.go"]
delay = 100
kill_delay = 500

[log]
time = true

[color]
app = "cyan"
build = "yellow"
main = "green"

[misc]
clean_on_exit = true
